modules/admin/controllers/IndexController.php
<?php
namespace app\modules\admin\controllers;
use app\models\User;
use app\modules\admin\models\LoginModel;
use app\modules\admin\models\ForgotModel;
use Yii;
use yii\web\Controller;
use yii\helpers\Url;

class IndexController extends Controller
{
    public function actionIndex() {
        $User = User::findOne(Yii::$app->user->getId());
        return $this->render('index', [
            'User'=>$User,
        ]);
    }

    public function actionLogin() {
        $LoginModel = new LoginModel;
        if ($LoginModel->load(Yii::$app->request->post()) && $LoginModel->login()) {
            $url = Yii::$app->session->has('admin_redirect_url') ?
                   Yii::$app->session->get('admin_redirect_url') :
                   Url::to(['index']);
            return $this->redirect($url);
        }
        $this->layout = 'login';
        return $this->render('login', [
            'LoginModel'=>$LoginModel,
        ]);
    }

    public function actionLogout() {
        Yii::$app->user->logout();
        $this->redirect(Url::to(['index']));
    }

    public function actionForgot() {
        $ForgotModel = new ForgotModel;
        $ForgotModel->scenario = ForgotModel::SCENARIO_FORGOT;
        if ($ForgotModel->load(Yii::$app->request->post())) {
            if ($ForgotModel->forgot('index/reset-password')) {
                Yii::$app->session->setFlash('message', \Yii::t('app', 'Please check your email'));
                return $this->refresh();                
            }
        }
        $this->layout = 'login';
        return $this->render('forgot', [
            'ForgotModel'=>$ForgotModel,
        ]);
    }

    public function actionResetPassword($forgot_key) {
        $ForgotModel = new ForgotModel;
        $ForgotModel->scenario = ForgotModel::SCENARIO_RESETPASS;
        if ($ForgotModel->load(Yii::$app->request->post())) {
            if ($ForgotModel->reset($forgot_key)) {
                Yii::$app->session->setFlash('message', \Yii::t('app', 'Your password was successfully changed'));
                return $this->refresh();
            }
        }
        $this->layout = 'login';
        return $this->render('reset-password', [
            'ForgotModel'=>$ForgotModel,
        ]);
    }
}

modules/admin/views/layouts/interface/breadcrumbs.php
<?php
use yii\helpers\Html;

/** @var yii\web\View $this */
?>
<?php if (!empty($this->params['breadcrumbs'])) { ?>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <?php foreach ($this->params['breadcrumbs'] as $title=>$link) { ?>
                    <?php if ($link) { ?>
                        <li><a href="<?=$link?>"><?=Html::encode($title);?></a></li>
                    <?php } else { ?>
                        <li class="active"><?=Html::encode($title);?></li>
                    <?php } ?>
                <?php } ?>
            </ol>
        </div>
    </div>
<?php } ?>

modules/admin/views/layouts/interface/buttons.php
<?php
use yii\helpers\Html;

/** @var yii\web\View $this */
?>
<?php if (!empty($this->params['buttons'])) { ?>
    <div class="row">
        <div class="col-lg-12">
            <div class="admin-action-btn btn-group btn-group-justified">
                <?php foreach ($this->params['buttons'] as $name=>$data) { ?>
                    <?php $icon = $data['icon'] ? '<i class="fa ' . $data['icon'] . '"></i>' : ''; ?>
                    <a class="btn btn-info" href="<?=$data['link']?>"><?=$icon?> <?=Html::encode($name);?></a>
                <?php } ?>
            </div>
        </div>
    </div>
<?php } ?>

modules/admin/views/layouts/interface/footer.php
    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

modules/admin/views/layouts/interface/head.php
<?php
use yii\helpers\Html;

/** @var yii\web\View $this */
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?=Html::encode($this->title); ?></h1>
    </div>
</div>

modules/admin/views/layouts/interface/header.php
<?php
use app\modules\admin\assets\AdminAsset;
use yii\helpers\Html;

/** @var yii\web\View $this */
AdminAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?=Yii::$app->language ?>">
<head>
    <meta charset="<?=Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="author" content="Alex Sergey"/>
    <?=Html::csrfMetaTags()?>
    <title><?=$this->title ? Html::encode($this->title) . ' | ' : '';?><?=Html::encode(Yii::$app->name);?> | <?=Yii::t('app', 'Admin Panel')?></title>
    <?php $this->head() ?>
</head>
<body class="<?=Yii::$app->controller->id?> <?=Yii::$app->controller->action->id?>">
    <?php $this->beginBody() ?>

modules/admin/views/layouts/interface/nav.php
<?php
use app\modules\admin\widgets\Navigation;
use yii\helpers\Html;
use yii\helpers\Url;
?>
<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only"><?=Yii::t('app', 'Navigation')?></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<?=Url::to(['/admin'])?>"><?=Html::encode(Yii::$app->name); ?></a>
    </div>
    <ul class="nav navbar-top-links navbar-right">
        <li class="pull-right">
            <a href="<?=Url::home(); ?>" target="_blank">
                <?=Yii::t('app', 'Go to site')?>
                <i class="fa fa-arrow-right"></i>
            </a>
        </li>
        <li class="dropdown pull-right">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>
                <?=Yii::t('app', 'Settings')?>
                <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <?php if (Yii::$app->user->can('admins')) { ?>
                    <li>
                        <a href="<?=Url::to(['user/edit', 'id'=>Yii::$app->user->getId()]);?>">
                            <i class="fa fa-user fa-fw"></i> <?=Yii::t('app', 'Your profile')?>
                        </a>
                    </li>
                    <li class="divider"></li>
                <?php } ?>
                <li><a href="<?=Url::to(['index/logout']) ?>"><i class="fa fa-sign-out fa-fw"></i><?=Yii::t('app', 'Logout')?></a></li>
            </ul>
        </li>
    </ul>
    <?=Navigation::widget(['active'=>isset($this->params['active']) ? $this->params['active'] : Yii::$app->controller->id]); ?>
</nav>